# Generated by Django 3.0.3 on 2020-11-15 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500, null=True)),
                ('starting_price', models.FloatField()),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('listing_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(default='http://127.0.0.1:8000/static/auctions/default.jpg')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Category')),
            ],
        ),
    ]
