# Generated by Django 3.0.3 on 2020-11-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201115_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='http://127.0.0.1:8000/static/auctions/default.jpg', upload_to='listing_images'),
        ),
    ]
