# Generated by Django 3.0.3 on 2020-11-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201121_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='listing_images/default.jpg', upload_to='listing_images'),
        ),
    ]
