# Generated by Django 3.0.3 on 2020-12-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
