# Generated by Django 3.0.3 on 2020-12-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201202_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='Listing',
            new_name='listing',
        ),
    ]
